spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/bevelop?serverTimezone=UTC
    password: '1234'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

jwt:
  token:
    access-token-secret-key: bevleop
    access-token-expire-length: 300000
    refresh-token-secret-key: backendBeVelop
    refresh-token-expire-length: 6000000

redis:
  host: localhost
  port: 6379