spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    url: jdbc:mysql://bevelop-rds-instance.c6qpo4nr80mp.ap-northeast-2.rds.amazonaws.com:3306/bevelop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/bevelop?serverTimezone=UTC
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  social:
    kakao:
      client_id: 2de06bd937541c3344ad869e4129aead
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
    github:
      client_id: d8fb40fbac72e115be1c
      client_secret: 6dc402a91ae9a613e01a1a50e49278b0f4a0948a
      redirect: /social/login/github
#      redirect: login/oauth2/code/github
      url:
        login: https://github.com/login/oauth/authorize
        token: https://github.com/login/oauth/access_token
        profile: https://api.github.com/user


  url:
    base: http://localhost:8080
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  redis:
    host: localhost
    port: 6379

jwt:
  token:
    access-token-secret-key: bevleop
    access-token-expire-length: 300000
    refresh-token-secret-key: backendBeVelop
    refresh-token-expire-length: 6000000

server:
  error:
    include-exception: true       # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부
